export const TASKS_ADD_TASK = "ADD_TASK";
export const TASKS_TOGGLE_STATUS_TASK = "TOGGLE_STATUS_TASK";
export const TASKS_REMOVE_TASK = "REMOVE_TASK";
export const TASKS_FETCH_ALL_TASKS = 'TASKS_FETCH_ALL_TASKS';

export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
